version: '3.11'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_entrypoint.sh:/ollama_entrypoint.sh
    entrypoint: ["/bin/bash", "/ollama_entrypoint.sh"]

  api-service:
    build: ./api-service
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama

  streamlit-ui:
    build: ./streamlit_ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api-service:8000
    depends_on:
      - api-service
